site_name: waterch-tasker
theme: material
nav:
  - Home: index.md
  - API:
      waterch.tasker:
        tasks: api/tasks.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/waterch/tasker
