__schema__ = "waterch.tasker.launcher.Launcher"
__name__ = "Example for tasker.decorator.def_task"
__author__ = "Chen Runze"
__version__ = "1.0.0"
__email__ = "chenrz925@bupt.edu.cn"
__abstract__ = ""

# ----- Global settings -----

[__setting__]
    [__setting__.storage]
    reference = "waterch.tasker.storages.basic.DictStorage$R"
        [__setting__.storage.kwargs]
    [__setting__.log]
        [__setting__.log.console]
        class = 'logging.StreamHandler'
        formatter = 'default'
        level = 'INFO'
        stream = 'ext://sys.stdout'

# ----- Task metainfo -----

[[__meta__]]
reference = "example_tasks.def_task.environ$T"
include = false
path = ""
profile = "print-0"
execute = true

[[__meta__]]
reference = "example_tasks.def_task.print$T"
include = false
path = ""
profile = "print-1"
execute = true

# ----- task profiles -----
[print-0]
TEST = 'TEST'
EXAMPLE = '100000'

[print-1]
text = 'f"hello\,world {2020}"$X'
