__schema__ = "waterch.tasker.launcher.Launcher"
__name__ = "MNIST AlexNet Example"
__author__ = "Chen Runze"
__version__ = "0.0.1"
__email__ = "chenrz925@icloud.com"
__abstract__ = "This profile is used to test the torch module in waterch.tasker.tasks."

[[__meta__]]
reference = "cifar_loader.CIFARDataLoaderTask:train"
include = false
path = ""
profile = "train_loader"
execute = true


[[__meta__]]
reference = "cifar_loader.CIFARDataLoaderTask:validate"
include = false
path = ""
profile = "validate_loader"
execute = true

[[__meta__]]
reference = "conv_train.ConvTrainTask:train"
include = false
path = ""
profile = "train"
execute = true

[__setting__]
    [__setting__.storage]
    reference = "waterch.tasker.storage.DictStorage"
    [__setting__.log]
    stdout = true
    level = "DEBUG"

[train_loader]
    [train_loader.dataset]
    simple = false
    reference = ""
        [train_loader.dataset.kwargs]
        train = true

    [train_loader.loader]
    batch_size = 1024
    shuffle = true
    num_workers = 2
    pin_memory = false
    drop_last = true

[validate_loader]
    [validate_loader.dataset]
    simple = false
    reference = ""
        [validate_loader.dataset.kwargs]
        train = false

    [validate_loader.loader]
    batch_size = 1024
    shuffle = true
    num_workers = 2
    pin_memory = false
    drop_last = true

[train]
device = "cpu"
non_blocking = true
max_epochs = 100
store_name = ""
    [train.data_loader]
    train = "train_loader"
    validate = "validate_loader"
    [train.optimizer]
    reference = "torch.optim.AdamW"
        [train.optimizer.kwargs]
        lr = 1e-3
    [train.loss]
    reference = "torch.nn.CrossEntropyLoss"
        [train.loss.kwargs]
    [train.model]