# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of example_tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # - name: pypi-publish
      # uses: pypa/gh-action-pypi-publish@v1.1.0
      # with:
        # PyPI user
        # user: __token__ # optional, default is __token__
        # Password for your PyPI user or an access token
        # password: ${{secrets.PYPI_TOKEN}}
        # repository_url: https://github.com/chenrz925/waterch-tasker.git
    - name: PyPI Deployment
      uses: chenrz925/deploy-pypi@master
      with:
        # PyPI password or API token
        password: ${{secrets.PYPI_TOKEN}}
        build: true
        skip_existing: true
